<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-10-05">
<meta name="description" content="risk of federal deficit and AI-related debt financing are not the main drivers">

<title>Expectation of real interest rates and inflation expectations are driving up the bond yields and mortgage rates – Yi Li</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-f806d9ca3cded21450884136ceca1cc5.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-32cf1dc2a8c62b25767500678f5cbd7c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Yi Li</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../blog/index.html"> 
<span class="menu-text">Writing</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../resume.html"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#two-decompositions" id="toc-two-decompositions" class="nav-link active" data-scroll-target="#two-decompositions">Two decompositions</a></li>
  <li><a href="#the-spreads-history" id="toc-the-spreads-history" class="nav-link" data-scroll-target="#the-spreads-history">The spread’s history</a></li>
  <li><a href="#decomposition-and-share-of-contribution" id="toc-decomposition-and-share-of-contribution" class="nav-link" data-scroll-target="#decomposition-and-share-of-contribution">Decomposition and share of contribution</a></li>
  <li><a href="#cleveland-feds-model-vs.-ny-feds-model" id="toc-cleveland-feds-model-vs.-ny-feds-model" class="nav-link" data-scroll-target="#cleveland-feds-model-vs.-ny-feds-model">Cleveland Fed’s model vs.&nbsp;NY Fed’s model</a></li>
  <li><a href="#what-moves-the-spread" id="toc-what-moves-the-spread" class="nav-link" data-scroll-target="#what-moves-the-spread">What moves the spread</a></li>
  <li><a href="#caveats" id="toc-caveats" class="nav-link" data-scroll-target="#caveats">Caveats</a></li>
  <li><a href="#takeaway" id="toc-takeaway" class="nav-link" data-scroll-target="#takeaway">Takeaway</a></li>
  <li><a href="#data-and-code" id="toc-data-and-code" class="nav-link" data-scroll-target="#data-and-code">Data and code</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Expectation of real interest rates and inflation expectations are driving up the bond yields and mortgage rates</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">interest rates</div>
    <div class="quarto-category">mortgages</div>
    <div class="quarto-category">FRED</div>
    <div class="quarto-category">Python</div>
    <div class="quarto-category">matplotlib</div>
  </div>
  </div>

<div>
  <div class="description">
    risk of federal deficit and AI-related debt financing are not the main drivers
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 5, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>The 30-Year Fixed Mortgage Rate is the most common type of U.S. home loan. As its name suggests, it takes borrowers 30 years to pay back the entire loan, and the interest rate is fixed at the then-current mortgage rate when the contract is signed. The mortgage rate has risen from 2.74% in January 2021 to 6.86% in September 2026. By the time this blog post is written, the national average is approximately 7.40% to 7.43%.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>The causes of the high level of mortgage rate are intricate, as they involve several layers of transmission, each layer represents stakeholders that are pertinent to the rates. The chain starts with the Federal Funds Rate. The Fed raises this rate in order to curb inflation, and the housing market is the main channel of monetary policy. The Fed cares about indirectly managing mortgages through raising the federal funds rate. This ultra short-term rate then directly affects the yields on 10-year Treasury, which is the benchmark of mortgage rates. Higher mortgage rates means home purchases are less affordable, and this matters to all potential homebuyers. According to Atlanta Fed, the median monthly payment of home purchase takes about 27.8% of a median household income in January 2021. Now it takes more than 45%, effectively deterring many buyers.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>The blog post tries to address two questions: how much of the rise is the Treasury yield, how much is the spread, and within the Treasury yield, is it expected real rates, expected inflation, or risk premia?</p>
<section id="two-decompositions" class="level2">
<h2 data-anchor-id="two-decompositions">Two decompositions</h2>
<p>The benchmark for mortgage rate is the 10-year Treasury yield. That is, mortgage rate tends to closely follow the 10-year Treasury (as opposed to the Federal Funds rate). The difference between the 30-year mortgage rate and the 10-year Treasury consists of two spreads: (i) secondary spread: prepayment risk, credit risk, and liquidity, (ii) primary-secondary spread: service fee, net guarantee fee, etc. This post will treat the two spreads as a whole and the equation is simply <span class="math inline">\text{mortgage rate} = \text{10-year Treasury yield} + \text{mortgage–Treasury spread}</span>. This is not only for simplicity, but more importantly, as we will discuss later in the post, the spread is not the main driver of the higher rates in the current period. Our focus is on the decomposition of the 10-year Treasury yield. The Cleveland Fed’s term-structure model breaks the 10-year Treasury yield into four components: expected path of real short rates, expected inflation, real risk premium, and inflation risk premium. The equation below gives a clearer representation of everything put together:</p>
<p><span class="math display">
\underbrace{i^{mort}_t}_{\text{mortgage rate}}
= \underbrace{\big(\bar r^{e}_t + \pi^{e}_t\big)}_{\text{expected policy path}}
+ \underbrace{\big(\rho^{real}_t + \rho^{\pi}_t\big)}_{\text{risk premia}}
+ \varepsilon_t + s_t
</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\bar r^{e}_t</span>: expected real interest rate (the average real short-term rate expected over the next ten years)</li>
<li><span class="math inline">\pi^{e}_t</span>: expected inflation rate</li>
<li><span class="math inline">\rho^{real}_t</span>: real risk premium</li>
<li><span class="math inline">\rho^{\pi}_t</span>: inflation risk premium</li>
<li><span class="math inline">\varepsilon_t</span>: Cleveland Fed’s model residual (the gap between the actual 10-year yield and the model’s fitted yield)</li>
<li><span class="math inline">s_t</span>: mortgage-Treasury spread</li>
</ul>
<p>Three data choices follow. All series are converted to monthly averages, so that weekly, daily and monthly data line up on the same dates. January 2021 is the base month for every “change since” calculation, because that is when the mortgage rate bottomed; a trough base maximizes the measured change by construction. The model residual is kept as its own piece, so that the six pieces add up exactly to the change in the mortgage rate.</p>
</section>
<section id="the-spreads-history" class="level2">
<h2 data-anchor-id="the-spreads-history">The spread’s history</h2>
<p><img src="fig1_levels.png" class="img-fluid"></p>
<p>Figure 1 gives a simple decomposition of the 30-year mortgage rate. The spread’s long-run norm is 1.69 pp on average from 2010 to 19, and it peaked at 2.97 pp in June 2023. It is now printing at 1.87 pp, which is just slightly above the long-run average pre-pandemic and post-GFC.</p>
</section>
<section id="decomposition-and-share-of-contribution" class="level2">
<h2 data-anchor-id="decomposition-and-share-of-contribution">Decomposition and share of contribution</h2>
<p><img src="fig2_contributions.png" class="img-fluid"></p>
<p>Figure 2 shows the complete decomposition of the mortgage rate. The blue bar indicates expected real short rates, which is the market’s expectation of future path of monetary policy. It has been the main driver of mortgage rates and 10-year Treasury for the majority of the sample period. We could see that even at the October 2023 peak, the spread was only a quarter of the story, and inflation expectation and expected real rates are predominantly leading.</p>
<div id="tbl-contrib" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-contrib-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Contributions to the change in the 30-year mortgage rate, percentage points and share of the total change. Shares can be negative or exceed 100 when pieces offset. Source: FRED (Freddie Mac PMMS, Federal Reserve Board H.15, Federal Reserve Bank of Cleveland); author’s calculations.
</figcaption>
<div aria-describedby="tbl-contrib-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Jan 2021 → Oct 2023 (pp)</th>
<th style="text-align: right;">%</th>
<th style="text-align: right;">Jan 2021 → Sep 2026 (pp)</th>
<th style="text-align: right;">%</th>
<th style="text-align: right;">Jan → Sep 2026 (pp)</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Expected real short rates</td>
<td style="text-align: right;">2.03</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">2.31</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">65</td>
</tr>
<tr class="even">
<td>Expected inflation</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="odd">
<td>Real risk premium</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td>Inflation risk premium</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td>Model residual</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-0.05</td>
<td style="text-align: right;">-7</td>
</tr>
<tr class="even">
<td>Mortgage-Treasury spread</td>
<td style="text-align: right;">1.17</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-0.02</td>
<td style="text-align: right;">-2</td>
</tr>
<tr class="odd">
<td>Total: 30-year mortgage rate</td>
<td style="text-align: right;">4.88</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">4.13</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>To get a more concrete sense of what’s driving the changes in mortgage rates, we could look at the share of contribution by components in three different periods, shown in the table above. The period from January 2021 to October 2023 saw rates from trough to peak, the main driver being the market’s expectation of the short-term policy rate (41%). The spread comes next at 24%. But if we look at a longer window from January 2021 to September 2026, the contribution of mortgage-Treasury spread shrinks to 5%. What’s more pertinent to the scope of this blog post is the year-to-date contribution. Since the beginning of 2026 until now, expected real short rates and expected inflation together accounts for 97% of the increase in mortgage rates.</p>
<p>To put those numbers into context, several forces have been pushing on different pieces of the decomposition. Fiscal concerns, such as the rising debt-to-GDP ratio and higher interest payments, would show up as a higher real risk premium, but that piece explains only part of the story. Higher energy prices would show up in the inflation risk premium, which is almost negligible at 1%. Debt issuance related to AI investment is not necessarily reflected in the model. Resilient economic growth feeds through to expected inflation.</p>
</section>
<section id="cleveland-feds-model-vs.-ny-feds-model" class="level2">
<h2 data-anchor-id="cleveland-feds-model-vs.-ny-feds-model">Cleveland Fed’s model vs.&nbsp;NY Fed’s model</h2>
<p>The Cleveland Fed’s model is only one way of decomposing the rates, and it would be conducive to check it against other models, such as New York Fed’s ACM model along with Treaury Inflations-Protected Securities (TIPS). THe table below shows that both models agree that expected policy path, not the term premium, is the main driver, and in 2026 both say all of it. TIPS data also supports the same framing. Over Jan 2021 and Sep 2026, the TIPS real yield rose 3.64 pp and the breakeven 0.27 pp, suggesting that the market believes the rise was almost all real. However, the models disagree on the exact contribution of term premium. From January 2021 to September 2026, while the Cleveland Fed’s model indicates that term premium contributes 0.23pp, the NY Fed’s model claims it contributes 1.31 pp. It is noteworthy that Cleveland’s expected inflation rose more than breakevens. Its model had 10-year expected inflation at 1.38% in January 2021 against a 2.08% breakeven.</p>
<div id="tbl-models" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Change in the 10-year Treasury yield and its parts under two models and in the TIPS market, percentage points. Source: FRED, Federal Reserve Bank of Cleveland, Federal Reserve Bank of New York (ACM); author’s calculations.
</figcaption>
<div aria-describedby="tbl-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Jan 2021 → Oct 2023</th>
<th style="text-align: right;">Jan 2021 → Sep 2026</th>
<th style="text-align: right;">Jan → Sep 2026</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cleveland: expected nominal path (real path + expected inflation)</td>
<td style="text-align: right;">3.01</td>
<td style="text-align: right;">3.51</td>
<td style="text-align: right;">0.73</td>
</tr>
<tr class="even">
<td>Cleveland: premia (real + inflation risk premium)</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.09</td>
</tr>
<tr class="odd">
<td>ACM: expected nominal path</td>
<td style="text-align: right;">2.87</td>
<td style="text-align: right;">2.57</td>
<td style="text-align: right;">0.72</td>
</tr>
<tr class="even">
<td>ACM: term premium</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">1.31</td>
<td style="text-align: right;">-0.02</td>
</tr>
<tr class="odd">
<td>TIPS: real yield</td>
<td style="text-align: right;">3.41</td>
<td style="text-align: right;">3.64</td>
<td style="text-align: right;">0.73</td>
</tr>
<tr class="even">
<td>TIPS: breakeven inflation</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.04</td>
</tr>
<tr class="odd">
<td>10-year Treasury yield (actual)</td>
<td style="text-align: right;">3.72</td>
<td style="text-align: right;">3.91</td>
<td style="text-align: right;">0.78</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="what-moves-the-spread" class="level2">
<h2 data-anchor-id="what-moves-the-spread">What moves the spread</h2>
<p><img src="fig3_spread_drivers.png" class="img-fluid"></p>
<p>Panel 1 shows that the spread spikes line up with the volatility spikes in 2008–09, spring 2020, and 2022–23. The mechanism is the prepayment option. A homeowner can refinance whenever rates fall, so the investor holding the mortgage is short that option. When rate volatility rises, the option is worth more and investors demand a wider spread to hold mortgages. Volatility went from about 50 bp in 2021 to about 145 bp in early 2023, and the spread from 1.4 pp to 2.97 pp. In Panel 2, the Fed’s balance sheet shows up in the spread too. The cleanest episode is 2009 wheb holdings go from zero to 1.1 trillion in about a year and the spread falls from 2.9 pp to 1.3 pp, even though volatility was still high. Since 2024, the Fed is still shrinking its holdings, yet the spread has come back to 1.87 pp, near its 2010–19 average. Volatility fell from ~140 bp to ~70 bp over the same period. So the recent normalization tracks volatility, not the Fed’s balance sheet, which suggests the prepayment-option channel is the stronger of the two.</p>
</section>
<section id="caveats" class="level2">
<h2 data-anchor-id="caveats">Caveats</h2>
<ul>
<li>The components for the decomposition are model estimates (Haubrich–Pennacchi–Ritchken), and a different model splits them differently (see <a href="#tbl-models" class="quarto-xref">Table&nbsp;2</a>) and we could potentially arrive at different conclusions. But in this case, different models at least agree with each other about the main driver.</li>
<li>The model does not fit the 10-year yield exactly. The residual averages −0.33 pp over the sample and reaches 1.23 pp in absolute value, but it moved only 0.17 pp between January 2021 and September 2026, so it does not change the ranking of the pieces.</li>
<li>The base month is the trough of the mortgage rate, which maximizes the measured change by construction. A later base, such as the first Fed cut in September 2024, would give smaller numbers but the same ordering.</li>
<li>The spread is the Freddie Mac survey rate minus the 10-year constant-maturity yield. It is not an MBS option-adjusted spread, so it mixes the secondary-market spread with lender margins and fees.</li>
</ul>
</section>
<section id="takeaway" class="level2">
<h2 data-anchor-id="takeaway">Takeaway</h2>
<p>To conclude, of the 4.13 pp rise in mortgage rates since January 2021, 3.91 is the Treasury yield and 0.22 is the spread. Within the Treasury yield, the expected path of real policy rates accounts for 2.31 pp (56% of the mortgage move) and expected inflation for 1.19.</p>
<p>Risk premia are small under the Cleveland model and about a third of the Treasury move under the NY Fed’s ACM model. The spread problem of 2023 has largely gone, but the rate problem has not.</p>
</section>
<section id="data-and-code" class="level2">
<h2 data-anchor-id="data-and-code">Data and code</h2>
<ul>
<li><strong>Mortgage rate:</strong> Freddie Mac Primary Mortgage Market Survey, 30-year fixed, via FRED (<code>MORTGAGE30US</code>), weekly. All FRED series were downloaded with <code>fredapi</code> on 4 October 2026.</li>
<li><strong>Treasury yields:</strong> Federal Reserve Board H.15, via FRED: 10-year constant maturity (<code>DGS10</code>), 10-year TIPS (<code>DFII10</code>), 10-year breakeven (<code>T10YIE</code>), daily.</li>
<li><strong>Fed MBS holdings:</strong> Federal Reserve Board H.4.1, via FRED (<code>WSHOMCB</code>), weekly.</li>
<li><strong>Yield decomposition:</strong> Federal Reserve Bank of Cleveland, <a href="https://www.clevelandfed.org/indicators-and-data/inflation-expectations">Inflation Expectations</a>, via FRED: <code>EXPINF10YR</code>, <code>REAINTRATREARAT10Y</code>, <code>TENEXPCHAREARISPRE</code>, <code>TENEXPCHAINFRISPRE</code>, monthly.</li>
<li><strong>Term premium cross-check:</strong> Federal Reserve Bank of New York, <a href="https://www.newyorkfed.org/research/data_indicators/term-premia-tabs">Treasury Term Premia</a> (Adrian, Crump and Moench), daily file, downloaded 3 October 2026.</li>
<li><strong>Affordability:</strong> Federal Reserve Bank of Atlanta, <a href="https://www.atlantafed.org/research-and-data/data/home-ownership-affordability-monitor">Home Ownership Affordability Monitor</a>.</li>
<li><strong>Code:</strong> <a href="https://github.com/1iiiiii/Mortgage-Rate-Decomposition">github.com/1iiiiii/Mortgage-Rate-Decomposition</a>. Four numbered notebooks download the data, build the monthly series and contributions, and save the figures and every number quoted above to <code>results/</code>.</li>
</ul>


<!-- -->

</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Freddie Mac’s Primary Mortgage Market Survey, which is the series used throughout this post, averaged 7.28% for the week of 1 October 2026 (7.03% the week before). <a href="https://www.globenewswire.com/news-release/2026/10/01/3373202/0/en/mortgage-rates-average-7-28.html">Freddie Mac, 1 October 2026</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Federal Reserve Bank of Atlanta, <a href="https://www.atlantafed.org/research-and-data/data/home-ownership-affordability-monitor">Home Ownership Affordability Monitor</a>: the share of median household income needed to cover the payment on a median-priced home, with 30% as the affordability threshold.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/1iiiiii\.github\.io\/Personal-Website\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Expectation of real interest rates and inflation expectations are driving up the bond yields and mortgage rates"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "risk of federal deficit and AI-related debt financing are not the main drivers"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2026-10-05</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [interest rates, mortgages, FRED, Python, matplotlib]</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>The 30-Year Fixed Mortgage Rate is the most common type of U.S. home loan. As its name suggests,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>it takes borrowers 30 years to pay back the entire loan, and the interest rate is fixed at the</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>then-current mortgage rate when the contract is signed. The mortgage rate has risen from </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>2.74% in January 2021 to 6.86% in September 2026. By the time this blog post is written, the national</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>average is approximately 7.40% to 7.43%.<span class="ot">[^pmms]</span> </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>The causes of the high level of</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>mortgage rate are intricate, as they involve several layers of transmission, each layer</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>represents stakeholders that are pertinent to the rates. The chain starts with the</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>Federal Funds Rate. The Fed raises this rate in order to curb inflation, and the housing</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>market is the main channel of monetary policy. The Fed cares about indirectly managing mortgages</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>through raising the federal funds rate. </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>This ultra short-term</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>rate then directly affects the yields on 10-year Treasury, which is the benchmark of mortgage rates. </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>Higher mortgage rates means home purchases are less affordable, and this matters</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>to all potential homebuyers.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>According to Atlanta Fed, the median monthly</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>payment of home purchase takes about 27.8% of a median household income in January 2021. Now it takes</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>more than 45%, effectively deterring many buyers.<span class="ot">[^hoam]</span> </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>The blog post tries to address two questions: how much of the</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>rise is the Treasury yield, how much is the spread, and within the Treasury yield, is it expected</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>real rates, expected inflation, or risk premia?</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="fu">## Two decompositions</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>The benchmark for mortgage rate is the 10-year Treasury yield. That is, mortgage rate tends</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>to closely follow the 10-year Treasury (as opposed to the Federal Funds rate). The difference</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>between the 30-year mortgage rate and the 10-year Treasury consists of two spreads: </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>(i) secondary spread: prepayment risk, credit risk, and liquidity, </span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>(ii) primary-secondary spread: service fee, net guarantee fee, etc.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>This post will treat the two spreads as a whole and the equation is simply </span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>$\text{mortgage rate} = \text{10-year Treasury yield} + \text{mortgage–Treasury spread}$. This is not only for simplicity, but more importantly, as we will</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>discuss later in the post, the spread is not the main driver of the higher rates in the current period. Our focus is</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>on the decomposition of the 10-year Treasury yield. The Cleveland Fed's term-structure model breaks the 10-year </span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>Treasury yield into four components: expected path of real short rates, expected inflation, real risk premium,</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>and inflation risk premium. The equation below gives a clearer representation of everything put together:</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>\underbrace{i^{mort}_t}_{\text{mortgage rate}}</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>= \underbrace{\big(\bar r^{e}_t + \pi^{e}_t\big)}_{\text{expected policy path}}</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>\underbrace{\big(\rho^{real}_t + \rho^{\pi}_t\big)}_{\text{risk premia}}</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>\varepsilon_t + s_t</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>where:</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\bar r^{e}_t$: expected real interest rate (the average real short-term rate expected over the next ten years)</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\pi^{e}_t$: expected inflation rate</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\rho^{real}_t$: real risk premium</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\rho^{\pi}_t$: inflation risk premium</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\varepsilon_t$: Cleveland Fed's model residual (the gap between the actual 10-year yield and the model's fitted yield)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$s_t$: mortgage-Treasury spread </span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>Three data choices follow. All series are converted to monthly averages, so that weekly, daily</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>and monthly data line up on the same dates. January 2021 is the base month for every "change</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>since" calculation, because that is when the mortgage rate bottomed; a trough base maximizes the</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>measured change by construction. The model residual is kept as its own piece, so that the six</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>pieces add up exactly to the change in the mortgage rate.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="fu">## The spread's history</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="al">![](fig1_levels.png)</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>Figure 1 gives a simple decomposition of the 30-year mortgage rate. The spread's long-run norm is</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>1.69 pp on average from 2010 to 19, and it peaked at 2.97 pp in June 2023. It is now printing at 1.87 pp,</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>which is just slightly above the long-run average pre-pandemic and post-GFC.</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="fu">## Decomposition and share of contribution</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="al">![](fig2_contributions.png)</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>Figure 2 shows the complete decomposition of the mortgage rate. The blue bar indicates expected real</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>short rates, which is the market's expectation of future path of monetary policy. It has been the main</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>driver of mortgage rates and 10-year Treasury for the majority of the sample period. We could see that even at </span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>the October 2023 peak, the spread was only a quarter of the story, and inflation expectation and </span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>expected real rates are predominantly leading. </span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="pp">|</span> Jan 2021 → Oct 2023 (pp) <span class="pp">|</span> % <span class="pp">|</span> Jan 2021 → Sep 2026 (pp) <span class="pp">|</span> % <span class="pp">|</span> Jan → Sep 2026 (pp) <span class="pp">|</span> % <span class="pp">|</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---:|---:|---:|</span></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Expected real short rates <span class="pp">|</span> 2.03 <span class="pp">|</span> 41 <span class="pp">|</span> 2.31 <span class="pp">|</span> 56 <span class="pp">|</span> 0.49 <span class="pp">|</span> 65 <span class="pp">|</span></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Expected inflation <span class="pp">|</span> 0.98 <span class="pp">|</span> 20 <span class="pp">|</span> 1.19 <span class="pp">|</span> 29 <span class="pp">|</span> 0.24 <span class="pp">|</span> 32 <span class="pp">|</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Real risk premium <span class="pp">|</span> 0.29 <span class="pp">|</span> 6 <span class="pp">|</span> 0.17 <span class="pp">|</span> 4 <span class="pp">|</span> 0.09 <span class="pp">|</span> 11 <span class="pp">|</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Inflation risk premium <span class="pp">|</span> 0.07 <span class="pp">|</span> 1 <span class="pp">|</span> 0.07 <span class="pp">|</span> 2 <span class="pp">|</span> 0.01 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Model residual <span class="pp">|</span> 0.35 <span class="pp">|</span> 7 <span class="pp">|</span> 0.17 <span class="pp">|</span> 4 <span class="pp">|</span> -0.05 <span class="pp">|</span> -7 <span class="pp">|</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Mortgage-Treasury spread <span class="pp">|</span> 1.17 <span class="pp">|</span> 24 <span class="pp">|</span> 0.22 <span class="pp">|</span> 5 <span class="pp">|</span> -0.02 <span class="pp">|</span> -2 <span class="pp">|</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Total: 30-year mortgage rate <span class="pp">|</span> 4.88 <span class="pp">|</span> 100 <span class="pp">|</span> 4.13 <span class="pp">|</span> 100 <span class="pp">|</span> 0.76 <span class="pp">|</span> 100 <span class="pp">|</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>: Contributions to the change in the 30-year mortgage rate, percentage points and share of the total change. Shares can be negative or exceed 100 when pieces offset. Source: FRED (Freddie Mac PMMS, Federal Reserve Board H.15, Federal Reserve Bank of Cleveland); author's calculations. {#tbl-contrib}</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>To get a more concrete sense of what's driving the changes in mortgage rates, we could look</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>at the share of contribution by components in three different periods, shown in the table above.</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>The period from January 2021 to October 2023 saw rates from trough to peak, the main driver</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>being the market's expectation of the short-term policy rate (41%). The spread comes next</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>at 24%. But if we look at a longer window from January 2021 to September 2026, the contribution</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>of mortgage-Treasury spread shrinks to 5%. What's more pertinent to the scope of this blog post</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>is the year-to-date contribution. Since the beginning of 2026 until now, expected real short</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>rates and expected inflation together accounts for 97% of the increase in mortgage rates. </span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>To put those numbers into context, several forces have been pushing on different pieces of the</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>decomposition. Fiscal concerns, such as the rising debt-to-GDP ratio and higher interest payments,</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>would show up as a higher real risk premium, but that piece explains only part of the story.</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>Higher energy prices would show up in the inflation risk premium, which is almost negligible at 1%.</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>Debt issuance related to AI investment is not necessarily reflected in the model. Resilient economic</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>growth feeds through to expected inflation.</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cleveland Fed's model vs. NY Fed's model</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>The Cleveland Fed's model is only one way of decomposing the rates, and it would be</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>conducive to check it against other models, such as New York Fed's ACM model along with </span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>Treaury Inflations-Protected Securities (TIPS). THe table below shows that both models</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>agree that expected policy path, not the term premium, is the</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>main driver, and in 2026 both say all of it. TIPS data also supports the same framing.</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>Over Jan 2021 and Sep 2026, the TIPS real yield rose 3.64 pp and the breakeven 0.27 pp,</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>suggesting that the market believes the rise was almost all real. </span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>However, the models disagree on the exact contribution of term premium. </span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>From January 2021 to September 2026, while the Cleveland Fed's model indicates that term premium</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>contributes 0.23pp, the NY Fed's model claims it contributes 1.31 pp.</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>It is noteworthy that Cleveland's expected inflation rose more than breakevens. Its model had</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>10-year expected inflation at 1.38% in January 2021 against a 2.08% breakeven.</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="pp">|</span> Jan 2021 → Oct 2023 <span class="pp">|</span> Jan 2021 → Sep 2026 <span class="pp">|</span> Jan → Sep 2026 <span class="pp">|</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cleveland: expected nominal path (real path + expected inflation) <span class="pp">|</span> 3.01 <span class="pp">|</span> 3.51 <span class="pp">|</span> 0.73 <span class="pp">|</span></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cleveland: premia (real + inflation risk premium) <span class="pp">|</span> 0.36 <span class="pp">|</span> 0.23 <span class="pp">|</span> 0.09 <span class="pp">|</span></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ACM: expected nominal path <span class="pp">|</span> 2.87 <span class="pp">|</span> 2.57 <span class="pp">|</span> 0.72 <span class="pp">|</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ACM: term premium <span class="pp">|</span> 0.91 <span class="pp">|</span> 1.31 <span class="pp">|</span> -0.02 <span class="pp">|</span></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> TIPS: real yield <span class="pp">|</span> 3.41 <span class="pp">|</span> 3.64 <span class="pp">|</span> 0.73 <span class="pp">|</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> TIPS: breakeven inflation <span class="pp">|</span> 0.30 <span class="pp">|</span> 0.27 <span class="pp">|</span> 0.04 <span class="pp">|</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 10-year Treasury yield (actual) <span class="pp">|</span> 3.72 <span class="pp">|</span> 3.91 <span class="pp">|</span> 0.78 <span class="pp">|</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>: Change in the 10-year Treasury yield and its parts under two models and in the TIPS market, percentage points. Source: FRED, Federal Reserve Bank of Cleveland, Federal Reserve Bank of New York (ACM); author's calculations. {#tbl-models}</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a><span class="fu">## What moves the spread</span></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a><span class="al">![](fig3_spread_drivers.png)</span></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>Panel 1 shows that the spread spikes line up with the volatility spikes in 2008–09, spring 2020, </span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>and 2022–23. The mechanism is the prepayment option. A homeowner can refinance whenever rates fall, </span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>so the investor holding the mortgage is short that option.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>When rate volatility rises, the option is worth more and investors demand a wider spread to hold mortgages. </span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>Volatility went from about 50 bp in 2021 to about 145 bp in early 2023, and the spread from 1.4 pp to 2.97 pp.</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>In Panel 2, the Fed's balance sheet shows up in the spread too. The cleanest episode is 2009</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>wheb holdings go from zero to 1.1 trillion in about a year and the spread falls from 2.9 pp to 1.3 pp, </span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>even though volatility was still high. </span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>Since 2024, the Fed is still shrinking its holdings, yet the spread has come back to 1.87 pp, </span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>near its 2010–19 average. Volatility fell from ~140 bp to ~70 bp over the same period. </span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>So the recent normalization tracks volatility, not the Fed's balance sheet, which suggests the prepayment-option channel is the stronger of the two.</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="fu">## Caveats</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The components for the decomposition are model estimates (Haubrich–Pennacchi–Ritchken), and a different model splits</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>  them differently (see @tbl-models) and we could potentially arrive at different conclusions. But in this case, different</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>  models at least agree with each other about the main driver.</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The model does not fit the 10-year yield exactly. The residual averages −0.33 pp over the sample</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>  and reaches 1.23 pp in absolute value, but it moved only 0.17 pp between January 2021 and September</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>  2026, so it does not change the ranking of the pieces.</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The base month is the trough of the mortgage rate, which maximizes the measured change by</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>  construction. A later base, such as the first Fed cut in September 2024, would give smaller</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>  numbers but the same ordering.</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The spread is the Freddie Mac survey rate minus the 10-year constant-maturity yield. It is not an</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>  MBS option-adjusted spread, so it mixes the secondary-market spread with lender margins and fees.</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a><span class="fu">## Takeaway</span></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>To conclude, of the 4.13 pp rise in mortgage rates since January 2021, 3.91 is the Treasury yield and 0.22 is</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>the spread. Within the Treasury yield, the expected path of real policy rates accounts for 2.31 pp</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>(56% of the mortgage move) and expected inflation for 1.19. </span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>Risk premia are small under the Cleveland model and about a third of the Treasury move under the</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>NY Fed's ACM model. The spread problem of 2023 has largely gone, but the rate problem has not.</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data and code</span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Mortgage rate:** Freddie Mac Primary Mortgage Market Survey, 30-year fixed, via FRED (<span class="in">`MORTGAGE30US`</span>), weekly. All FRED series were downloaded with <span class="in">`fredapi`</span> on 4 October 2026.</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Treasury yields:** Federal Reserve Board H.15, via FRED: 10-year constant maturity (<span class="in">`DGS10`</span>), 10-year TIPS (<span class="in">`DFII10`</span>), 10-year breakeven (<span class="in">`T10YIE`</span>), daily.</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Fed MBS holdings:** Federal Reserve Board H.4.1, via FRED (<span class="in">`WSHOMCB`</span>), weekly.</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Yield decomposition:** Federal Reserve Bank of Cleveland, <span class="co">[</span><span class="ot">Inflation Expectations</span><span class="co">](https://www.clevelandfed.org/indicators-and-data/inflation-expectations)</span>, via FRED: <span class="in">`EXPINF10YR`</span>, <span class="in">`REAINTRATREARAT10Y`</span>, <span class="in">`TENEXPCHAREARISPRE`</span>, <span class="in">`TENEXPCHAINFRISPRE`</span>, monthly.</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Term premium cross-check:** Federal Reserve Bank of New York, <span class="co">[</span><span class="ot">Treasury Term Premia</span><span class="co">](https://www.newyorkfed.org/research/data_indicators/term-premia-tabs)</span> (Adrian, Crump and Moench), daily file, downloaded 3 October 2026.</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Affordability:** Federal Reserve Bank of Atlanta, <span class="co">[</span><span class="ot">Home Ownership Affordability Monitor</span><span class="co">](https://www.atlantafed.org/research-and-data/data/home-ownership-affordability-monitor)</span>.</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Code:** <span class="co">[</span><span class="ot">github.com/1iiiiii/Mortgage-Rate-Decomposition</span><span class="co">](https://github.com/1iiiiii/Mortgage-Rate-Decomposition)</span>. Four numbered notebooks download the data, build the monthly series and contributions, and save the figures and every number quoted above to <span class="in">`results/`</span>.</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="ot">[^pmms]: </span>Freddie Mac's Primary Mortgage Market Survey, which is the series used throughout this post, averaged 7.28% for the week of 1 October 2026 (7.03% the week before). <span class="co">[</span><span class="ot">Freddie Mac, 1 October 2026</span><span class="co">](https://www.globenewswire.com/news-release/2026/10/01/3373202/0/en/mortgage-rates-average-7-28.html)</span>.</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a><span class="ot">[^hoam]: </span>Federal Reserve Bank of Atlanta, <span class="co">[</span><span class="ot">Home Ownership Affordability Monitor</span><span class="co">](https://www.atlantafed.org/research-and-data/data/home-ownership-affordability-monitor)</span>: the share of median household income needed to cover the payment on a median-priced home, with 30% as the affordability threshold.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><img src="../../../images/UniversityofPennsylvania_FullLogo_RGB.png" class="img-fluid" width="112"></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>© 2026 Yi Li · Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>